FROM ubuntu:latest

RUN apt-get update && \
    apt-get -y install \
    mariadb-client \
    cron

RUN touch /var/log/cron.log

ARG cronInterval
ARG MYSQL_USER
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_DATABASE

RUN (crontab -l ; echo "$cronInterval /usr/bin/mysqldump -u${MYSQL_USER} -p${MYSQL_ROOT_PASSWORD} -h mysql ${MYSQL_DATABASE} > /root/backup/${MYSQL_DATABASE}_backup.sql") | crontab

CMD printenv | cron && tail -f /var/log/cron.log